#this will build a java project with maven
name: Java CI with Maven on linux

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: corretto
    - name: Cache m2 folder
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: m2-
    - name: Build with Maven
      run: >
        xvfb-run
        mvn verify
        -Pjacoco
        -Pmutation-testing
        sonar:sonar 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Coveralls
      #full hash requested by sonar for security githubactions:S7637
      uses: coverallsapp/github-action@0a51d2e0b5417d06e4ecceb534aec87defc53926
